name: "Snyk OSS Scan  "
on: push

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk OSS Scan'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       
    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v1

    # Install and Authenticate to Snyk
    - name: Install Snyk & Authenticate
      run: |
         sudo npm install -g snyk
         snyk auth ${SNYK_TOKEN}
         
    # Run Snyk OSS
    - name: Run OSS Code
      run: |
         snyk test 
      continue-on-error: true
